---
name: pytest-language-server
description: A blazingly fast LSP implementation for pytest, built with Rust.
homepage: https://github.com/bellini666/pytest-language-server
licenses:
  - MIT
languages:
  - Python
categories:
  - LSP

source:
  id: pkg:pypi/pytest-language-server@0.18.0

bin:
  pytest-language-server: pypi:pytest-language-server

neovim:
  lspconfig: pytest_lsp
